services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'

  watchthisshit.api:
    image: watchthisshit.api
    build:
      context: .
      dockerfile: WatchThisShit.API/Dockerfile